### ISSUE TITLE
git lfs pull issue

### ISSUE THREAD

**Issue by loveJasmine** [tlatkowski/multihead-siamese-nets#8]
(venv) :multihead-siamese-nets $ git lfs pull
batch response: This repository is over its data quota. Purchase more data packs to restore access.                                                                         
error: failed to fetch some objects from 'https://github.com/tlatkowski/multihead-siamese-nets.git/info/lfs'
(venv) :multihead-siamese-nets $

**Comment by tlatkowski** [comment]
Thanks for reporting issue, i will solve it in some spare time.

**Comment by tlatkowski** [comment]
Got rid of git-lfs, issue solved.
