### ISSUE TITLE
do you process the unknown words?

### ISSUE THREAD

**Issue by xy-always** [tlatkowski/multihead-siamese-nets#9]
I found that if the sentence have the unknown word, this program will go wrong.

**Comment by tlatkowski** [comment]
Hi, what do you mean by go wrong? Could you provide more details?

I looked into DatasetVectorizer class and it seems that i haven't implemented out-of-vocabulary token case.

**Comment by tlatkowski** [comment]
that's right, it looks like a bug related to OOV token - current version of code does not support OOV token.

**Comment by xy-always** [comment]
ok, thanks.

**Comment by tlatkowski** [comment]
one additional question, have you encountered this issue during the training time?
